name: overseerr
services:
  overseerr:
    image: linuxserver/overseerr:1.33.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: Specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Contains all relevant configuration files.
      ports:
        - container: "5055"
          description:
            en_us: Port for Overseerr's web interface.
    ports:
      - target: 5055
        published: 5055
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/overseerr/config
        target: /config
    container_name: overseerr
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: overseerr
  description:
    en_us: Overseerr is a free and open source software application for managing requests for your media library. It integrates with your existing services, such as Sonarr, Radarr, and Plex!
  tagline:
    en_us: Overseerr is a request management and media discovery tool built to work with your existing Plex ecosystem.
  developer: LinuxServer.io
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Overseerr/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Overseerr/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Overseerr/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Overseerr/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Overseerr/thumbnail.png
  title:
    en_us: Overseerr
  category: Media
  port_map: "5055"