name: resilio-sync
services:
  resilio-sync:
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    image: lscr.io/linuxserver/resilio-sync:2.7.3
    network_mode: bridge
    ports:
      - target: 55555
        published: "55555"
        protocol: tcp
      - target: 8888
        published: "8888"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/data
        target: /sync
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
    privileged: false
    container_name: resilio-sync
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  description:
    en_us: resilio-sync is a Docker-based application that enables fast and secure file synchronization and sharing.
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Resilio-sync/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Resilio-sync/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Resilio-sync/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Resilio-sync/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Resilio-sync/thumbnail.jpg
  tagline:
    en_us: Unleash the power of seamless file synchronization.
  author: Mypancho.com
  category: File Sync
  hostname: ""
  index: /
  port_map: "8888"
  scheme: http
  store_app_id: resilio-sync
  title:
    en_us: resilio-sync