name: plex
services:
  app:
    container_name: plex
    image: plexinc/pms-docker
    environment:
      - PLEX_CLAIM=<REPLACE WITH code from https://www.plex.tv/claim/>
      - TZ=$TZ
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/transcode
        target: /transcode
      - type: bind
        source: /DATA/Media
        target: /media
    restart: unless-stopped
    network_mode: host
    privileged: false

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: Mypancho.com
  category: Media
  description:
    en_us: Plex is the ultimate entertainment platform that allows you to stream movies, TV shows, and music. It is available on a wide range of devices and offers a unique combination of free ad-supported content, live TV, and an extensive catalog of titles from various streaming services. With Plex, you can easily search for and add any title to your Watchlist, regardless of the streaming service it belongs to. With a growing user base of 17 million active users, Plex serves as a trusted entertainment concierge, providing recommendations and new discoveries from all your favorite streaming apps and personal media libraries.
  developer: plex
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/plex/icon.png
  index: /web
  main: app
  port_map: "32400"
  scheme: http
  tips:
    before_install:
      en_us: |
          Instractions and installation available here: https://github.com/mariosemes/CasaOS-TMCstore/tree/main/Apps/plex
    en_us: |
      Instractions and installation available here: https://github.com/mariosemes/CasaOS-TMCstore/tree/main/Apps/plex
  tagline:
    en_us: The ultimate entertainment platform for movies, shows, music
  store_app_id: plex-Panchocloud
  title:
    en_us: Plex  
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/plex/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/plex/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/plex/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/plex/thumbnail.jpg