name: handbrake
services:
  handbrake:
    image: jlesage/handbrake:v23.06.1
    network_mode: bridge
    ports:
      - target: 5800
        published: "5800"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA
        target: /storage
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/watch
        target: /watch
      - type: bind
        source: /DATA/Media
        target: /output
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/config
        target: /config
    container_name: handbrake
x-casaos:
  architectures:
    - amd64
  description:
    en_us: Handbrake is a Docker-based application for video transcoding and compression, offering powerful and flexible multimedia processing across multiple platforms.
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Handbrake/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Handbrake/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Handbrake/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Handbrake/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Handbrake/thumbnail.jpg
  tagline:
    en_us: Liberate your videos and unleash infinite possibilities.
  author: Mypancho.com
  category: Media
  hostname: ""
  index: /
  port_map: "5800"
  scheme: http
  store_app_id: handbrake
  title:
    en_us: handbrake
