# Name of the application
name: appsmith

# Service definitions for the application
services:
  # Service name: app
  # The `app` service definition
  app:
    image: appsmith/appsmith-ee:v1.9.42 # Docker image to use
    container_name: appsmith # Name of the container
    ports:
      - "1080:80" # Port mapping host:container for HTTP
      - "10443:443" # Port mapping host:container for HTTPS
    volumes:
      - /DATA/AppData/$AppID/stacks:/appsmith-stacks # Mount volume for app data
    restart: unless-stopped # Container restart policy
    x-casaos: # CasaOS specific configuration
      volumes:
        - container: /appsmith-stacks
          description:
            en_us: "Container Path: /appsmith-stacks" # Description of the volume
      ports:
        - container: "1080"
          description:
            en_us: "Container Port: 1080" # Description of the HTTP port
        - container: "10443"
          description:
            en_us: "Container Port: 10443" # Description of the HTTPS port

# CasaOS specific configuration
x-casaos:
  # Supported CPU architectures for the application
  architectures:
    - amd64
    - arm64
  # Main service of the application
  main: app
  description:
    # Description in English
    en_us: Low code project to build admin panels, internal tools, and dashboards, integrating 15+ databases.
  tagline:
    # Short description or tagline in English
    en_us: Simplified development of admin panels and dashboards
  # Developer's name or identifier
  developer: "appsmithorg"
  # Author of this configuration
  author: Mypancho.com
  # Icon for the application
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/appsmith/icon.png
  screenshot_link:
    - https://github.com/uche40/Dev-Pancho-Cloud-App-Store/tree/main/Apps/appsmith/screenshot-1.PNG
    - https://github.com/uche40/Dev-Pancho-Cloud-App-Store/tree/main/Apps/appsmith/screenshot-2.PNG
    - https://github.com/uche40/Dev-Pancho-Cloud-App-Store/tree/main/Apps/appsmith/screenshot-3.PNG
  thumbnail: https://github.com/uche40/Dev-Pancho-Cloud-App-Store/tree/main/Apps/appsmith/thumbnail.PNG  
  title:
    # Title in English
    en_us: Appsmith
  # Application category
  category: Widget
  # Port mapping information
  port_map: "1080"