# Configuration for focalboard setup

# Application Name
name: focalboard

# Services used in the application
services:
  # The `app` service for the Focalboard application
  app:
    # Name of the container
    container_name: focalboard
    # Docker image to be used
    image: mattermost/focalboard:7.11.4
    # Restart policy for the service
    restart: unless-stopped
    # Port mappings for the service
    ports:
      - "8000:8000"
    # Network mode for the service
    network_mode: bridge
    # Volumes for the service HOST -> CONTAINER
    volumes:
      - /DATA/AppData/$AppID/data:/opt/focalboard/data
    # CasaOS specific configuration for the app service
    x-casaos:
      volumes:
        - container: /opt/focalboard/data
          description:
            en_us: "Container Path: /opt/focalboard/data"
      ports:
        - container: "8000"
          description:
            en_us: "Container Port: 8000"

# CasaOS global application configuration
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
  # Main service for this application
  main: app
  # Detailed description for the application
  description:
    en_us: Focalboard is a self-hosted, open-source project management tool with multilingual support. It serves as an alternative to popular services like Trello, Notion, and Asana, providing users with a versatile and customizable platform for organizing and managing various projects and tasks.
  # Brief tagline for the application
  tagline:
    en_us: Focalboard is an open-source Trello, Notion, Asana alternative.
  # Developer's information
  developer: "mattermost"
  # Author of this particular configuration
  author: Mypancho.com
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/focalboard/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/focalboard/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/focalboard/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/focalboard/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/focalboard/thumbnail.jpg
  # Title for the application
  title:
    en_us: Focalboard
  # Category under which the application falls
  category: Utility
  # Default port mapping for the application
  port_map: "8000"
  # This is shown before installing
  tips:
    before_install:
      en_us: |
        You will need to create a new account.