# Configuration for onlyoffice setup
name: onlyoffice

# Service definitions for the application
services:
  app:
    image: onlyoffice/documentserver
    container_name: documentserver
    ports:
      - "7400:80"
    volumes:
      - /DATA/AppData/$AppID/onlyoffice/logs:/var/log/onlyoffice
      - /DATA/AppData/$AppID/onlyoffice/data:/var/www/onlyoffice/Data
      - /DATA/AppData/$AppID/onlyoffice/lib:/var/lib/onlyoffice
      - /DATA/AppData/$AppID/onlyoffice/rabbitmq:/var/lib/rabbitmq
      - /DATA/AppData/$AppID/onlyoffice/redis:/var/lib/redis
      - /DATA/AppData/$AppID/onlyoffice/db:/var/lib/postgresql
    x-casaos: # CasaOS specific configuration
      volumes:
        - container: /var/log/onlyoffice
          description:
            en_us: "Container Path: /var/log/onlyoffice"
        - container: /var/www/onlyoffice/Data
          description:
            en_us: "Container Path: /var/www/onlyoffice/Data"
        - container: /var/lib/onlyoffice
          description:
            en_us: "Container Path: /var/lib/onlyoffice"
        - container: /var/lib/rabbitmq
          description:
            en_us: "Container Path: /var/lib/rabbitmq"
        - container: /var/lib/redis
          description:
            en_us: "Container Path: /var/lib/redis"
        - container: /var/lib/postgresql
          description:
            en_us: "Container Path: /var/lib/postgresql"
      ports:
        - container: "80"
          description:
            en_us: "Container Port: 80"

# CasaOS specific configuration
x-casaos:
  architectures: # Supported CPU architectures
    - amd64
    - arm64
  main: app # Main service of the application
  description:
    en_us: ONLYOFFICE Docs is a no-cost, web-based collaborative office suite that includes viewers and editors for documents, spreadsheets, and presentations. It also supports forms and PDFs, ensuring complete compatibility with Office Open XML formats.
 # Description in English
  tagline:
    en_us: Collaborative office suite for texts, spreadsheets, and presentations. # Short description or tagline in English
  developer: "documentserver" # Developer's name or identifier
  author: Mypancho.com # Author of this configuration
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/onlyoffice/icon.png
  screenshot_link:
    - https://github.com/uche40/Dev-Pancho-Cloud-App-Store/tree/main/Apps/onlyoffice/screenshot-1.PNG
    - https://github.com/uche40/Dev-Pancho-Cloud-App-Store/tree/main/Apps/onlyoffice/screenshot-2.PNG
    - https://github.com/uche40/Dev-Pancho-Cloud-App-Store/tree/main/Apps/onlyoffice/screenshot-3.PNG
  thumbnail: https://github.com/uche40/Dev-Pancho-Cloud-App-Store/tree/main/Apps/onlyoffice/thumbnail.PNG
  title:
    en_us: OnlyOffice # Title in English
  category: Utility # Application category
  port_map: "7400" # Port mapping information