name: calibre-web
services:
  calibre-web:
    environment:
      DOCKER_MODS: ghcr.io/linuxserver/mods:universal-calibre
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: linuxserver/calibre-web:0.6.20
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8083
        published: "8083"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Media/Books
        target: /books
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
        - container: DOCKER_MODS
          description:
            en_us: ""
      ports:
        - container: "8083"
          description:
            en_us: ""
      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /books
          description:
            en_us: ""
    container_name: calibre-web
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: calibre-web
  author: Mypancho.com
  category: Media
  description:
    en_us: Calibre-web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database. It is also possible to integrate google drive and edit metadata and your calibre library through the app itself.
  developer: linuxserver
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Calibre-web/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Calibre-web/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Calibre-web/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Calibre-web/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Calibre-web/thumbnail.png
  tagline:
    en_us: Web app for browsing, reading and downloading eBooks stored in a Calibre database
  tips:
    before_install:
      en_us: |
        | Username | Password |
        | -------- | -------- |
        | `admin`    | `admin123` |
      zh_cn: |
        | 用户名 | 密码 |
        | -------- | -------- |
        | `admin`    | `admin123` |
  title:
    en_us: Calibre-web
  index: /
  port_map: "8083"
