name: openspeedtest
services:
  openspeedtest:
    image: openspeedtest/latest:v2.0.3
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 3000
        published: "3004"
        protocol: tcp
    restart: always
    x-casaos:
      ports:
        - container: "3000"
          description:
            en_us: ""
    container_name: openspeedtest
x-casaos:
  architectures:
    - amd64
    - arm64
    - ppc64le
    - s390x
    - "386"
    - arm
  main: openspeedtest
  author: Mypancho.com
  category: Utilities
  description:
    en_us: An application for launching HTML5 Network Speed Test Server. You can test download & upload speed from any device within your network with a web browser that is IE10 or new.
  developer: OpenSpeedTest
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/OpenSpeedTest/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/OpenSpeedTest/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/OpenSpeedTest/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/OpenSpeedTest/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/OpenSpeedTest/thumbnail.jpg
  tagline:
    en_us: HTML5 Network Speed Test Server.
  tips: {}
  title:
    en_us: OpenSpeedTest
  index: /
  port_map: "3004"
