name: node-red
services:
  node-red:
    image: nodered/node-red:3.1
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: host
    ports:
      - target: 1880
        published: "1880"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/data
        target: /data
    x-casaos:
      ports:
        - container: "1880"
          description:
            en_us: ""
      volumes:
        - container: /data
          description:
            en_us: ""
    container_name: node-red
x-casaos:
  architectures:
    - amd64
    - arm64
    - s390x
    - arm
  main: node-red
  author: Mypancho.com
  category: Developer
  description:
    en_us: Node-RED is a programming tool for wiring together hardware devices, APIs and online services in new and interesting ways.  It provides a browser-based editor that makes it easy to wire together flows using the wide range of nodes in the palette that can be deployed to its runtime in a single-click.
  developer: Node-RED
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Node-RED/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Node-RED/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Node-RED/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Node-RED/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Node-RED/thumbnail.png
  tagline:
    en_us: Low-code programming for event-driven applications
  tips: {}
  title:
    en_us: Node-RED
  index: /
  port_map: "1880"
