# Name of the application
name: flame

# List of services that this application uses
services:
  # Main service for the Flame application
  app:
    # The Docker image to be used for the Flame application
    image: pawelmalak/flame:multiarch2.3.1

    # Environment variables that configure the application
    environment:
      # Specifies the password to be used by the Flame application
      PASSWORD: casaos

    # Policy to determine how the service should be restarted if it stops
    restart: unless-stopped

    # Specifies the ports that the application should expose
    ports:
      # Maps the container's port (target) to the host's port (published)
      - target: 8103
        published: "8103"
        protocol: tcp

    # Specifies the storage volumes that the application should use
    volumes:
      # Mounts the application data directory from the host system to the container
      - type: bind
        source: /DATA/AppData/$AppID/flame/data
        target: /flame/data

      # Mounts the Docker socket from the host system to the container
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

# CasaOS specific configuration for the application
x-casaos:
  # List of architectures that this application supports
  architectures:
    - amd64
    - arm
    - arm64

  # Indicates the main service for this application within the services list
  main: app

  # Provides a detailed description of the application
  description:
    en_us:
      Flame, a self-hosted startpage for your server, draws heavy inspiration from SUI in its design. It prioritizes user-friendliness and offers easy setup. Its built-in editors enable users to effortlessly establish their own application hub without the need for any file editing.

  # Provides a short and catchy tagline for the application
  tagline:
    en_us: Flame is a user-friendly, SUI-inspired startpage for self-hosted servers. No coding required. 

  # Name of the developer or organization that developed the application
  developer: "flame"

  # Indicates the person or organization responsible for creating this configuration
  author: Mypancho.com

  # URL pointing to the icon for the application
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/flame/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/flame/screenshot-1.PNG
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/flame/screenshot-2.PNG
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/flame/screenshot-3.PNG
  # URL pointing to a thumbnail image representing the application
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/cAdvisor/thumbnail.PNG

  # Provides a title for the application
  title:
    en_us: Flame

  # Specifies the category under which the application falls
  category: Entertainment

  # Specifies the port on which the application is accessible
  port_map: "8103"
