name: databag
services:
  databag:
    image: balzack/databag:0.1.7
    restart: unless-stopped
    x-casaos:
      volumes:
        - container: /var/lib/databag
          description:
            en_us: database and asset store
      ports:
        - container: "7000"
          description:
            en_us: rest api port
    ports:
      - target: 7000
        published: 7000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/databag/data
        target: /var/lib/databag
    container_name: databag
x-casaos:
  architectures:
    - amd64
    - arm64
  main: databag
  description:
    en_us: Databag is a federated chat app for self-hosting that focuses on user privacy and security; the service includes clients for iOS, Android, and browser.
  tagline:
    en_us: Messenger for the Decentralized Web
  developer: balzack
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Databag/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Databag/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Databag/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Databag/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Databag/thumbnail.jpg
  author: Mypancho.com
  category: Chat
  title:
    en_us: Databag
  port_map: "7000"
