name: draw-io
services:
  app:
    image: jgraph/drawio:21.7.5
    restart: unless-stopped
    environment:
      LETS_ENCRYPT_ENABLED: false
      PUBLIC_DNS: ''
    x-casaos:
      envs: []
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/log/letsencrypt
        target: /var/log/letsencrypt
      - type: bind
        source: /DATA/AppData/$AppID/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: /DATA/AppData/$AppID/lib/letsencrypt
        target: /var/lib/letsencrypt
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: draw-io (formerly Diagramly) is free online diagram software. You can use it as a flowchart maker, network diagram software, to create UML online, as an ER diagram tool, to design database schema, to build BPMN online, as a circuit diagram maker, and more. draw-io can import .vsdx, Gliffy™ and Lucidchart™ files.
  tagline:
    en_us: Free online diagram software with diverse diagram creation capabilities.
  developer: jgraph
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/draw-io/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/draw-io/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/draw-io/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/draw-io/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/draw-io/thumbnail.jpg
  title:
    en_us: Draw.io
  category: Utility
  port_map: '8080'
