# Configuration for code-server setup
name: code-server
# Service definitions for the code-server application
services:
  # Service name: app
  app:
    image: codercom/code-server:latest # The Docker image to use (latest version of code-server)
    container_name: code-server # Name of the container instance
    environment:
      - PASSWORD=my_password # Password to access code-server
      - PUID=1000 # User ID under which code-server will run
      - PGID=1000 # Group ID under which code-server will run
    volumes: 
      - /DATA/AppData/$AppID/code-server:/home/coder/code-server # Mounting the project directory inside the container
    ports:
      - "8282:8282" # Expose code-server's port 8282 on the host's port 8282
    restart: always # Policy to restart the container if it stops unexpectedly

# CasaOS specific configuration
x-casaos:
  architectures: # Supported CPU architectures
    - amd64
    - arm64
  main: app # Main service of the application
  description:
    en_us: Code-server is a web-based code editing platform that allows developers to write, edit, and collaboratge on code remotely. It provides a full-featured code editor, supporting syntax highligthing, code completion, and debugging. With code-server, developers can access their coding environment from any browser and device, making it convenient for working on projects or collaborating with others. It also offers extensions and plugins to customise the editor according to individual preferences. # Description in English
  tagline:
    en_us: Access VS-code in browser and run anywhere # Short description or tagline in English
  developer: "Coder" # Developer's name or identifier
  author: Mypancho.com # Author of this configuration
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/code-server/icon.png # Icon for the application
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/code-server/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/code-server/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/code-server/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/code-server/thumbnail.jpg # Thumbnail image 
  title:
    en_us: Code Server # Title in English
  category: Development Tools # Application category
  port_map: "8282" # Port mapping information
