name: oscam
services:
  app:
    image: linuxserver/oscam:version-11725
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Config
      ports:
        - container: '8888'
          description:
            en_us: Webgui
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/oscam/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: An Open Source Conditional Access Module software used for descrambling DVB transmissions using smart cards. It's both a server and a client.
  tagline:
    en_us: Open-source software for descrambling DVB transmissions via smart cards.
  developer: streamboard
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/oscam/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/oscam/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/oscam/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/oscam/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/oscam/thumbnail.jpg
  title:
    en_us: Oscam
  category: Utility
  project_url: http://www.streamboard.tv/oscam/
  port_map: '8888'
