name: mariadb
services:
  mariadb:
    image: linuxserver/mariadb:10.11.5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MYSQL_ROOT_PASSWORD: casaos
      MYSQL_DATABASE: casaos
      MYSQL_USER: casaos
      MYSQL_PASSWORD: casaos
      REMOTE_SQL: ""
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: Set this to root password for installation (minimum 4 characters & non-alphanumeric passwords must be properly escaped).
        - container: MYSQL_DATABASE
          description:
            en_us: Specify the name of a database to be created on image startup.
        - container: MYSQL_USER
          description:
            en_us: This user will have superuser access to the database specified by MYSQL_DATABASE (do not use root here).
        - container: MYSQL_PASSWORD
          description:
            en_us: Set this to the password you want to use for you MYSQL_USER (minimum 4 characters & non-alphanumeric passwords must be properly escaped).
        - container: REMOTE_SQL
          description:
            en_us: Set this to ingest sql files from an http/https endpoint (comma seperated array).
    ports:
      - target: 3306
        published: "3306"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/mariadb/config
        target: /config
    container_name: mariadb
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: mariadb
  description:
    en_us: |
      MariaDB Server is one of the most popular open source relational databases. It’s made by the original developers of MySQL and guaranteed to stay open source. It is part of most cloud offerings and the default in most Linux distributions.
      It is built upon the values of performance, stability, and openness, and MariaDB Foundation ensures contributions will be accepted on technical merit. Recent new functionality includes advanced clustering with Galera Cluster 4, compatibility features with Oracle Database and Temporal Data Tables, allowing one to query the data as it stood at any point in the past.
  tagline:
    en_us: MariaDB Server is one of the most popular database servers in the world. It's made by the original developers of MySQL and guaranteed to stay open source.
  developer: MariaDB Foundation
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/MariaDB/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/MariaDB/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/MariaDB/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/MariaDB/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/MariaDB/thumbnail.jpg
  tips:
    before_install:
      en_us: |
        Default user: `casaos`
        Default password: `casaos`
        Default database: `casaos`

        Default root password: `casaos`
  title:
    en_us: MariaDB
  category: Developer
