name: sabnzbd
services:
  sabnzbd:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/sabnzbd:4.0.3
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8080
        published: "8282"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Downloads
        target: /incomplete-downloads
      - type: bind
        source: /DATA/AppData/Panchocloud/sabnzbd/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
      ports:
        - container: "8080"
          description:
            en_us: ""
      volumes:
        - container: /incomplete-downloads
          description:
            en_us: ""
        - container: /config
          description:
            en_us: ""
        - container: /downloads
          description:
            en_us: ""
    container_name: sabnzbd
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: sabnzbd
  author: Mypancho.com
  category: Media
  description:
    en_us: SABnzbd is an Open Source Binary Newsreader written in Python. It's totally free, easy to use, and works practically everywhere. SABnzbd makes Usenet as simple and streamlined as possible by automating everything we can. All you have to do is add an .nzb. SABnzbd takes over from there, where it will be automatically downloaded, verified, repaired, extracted and filed away with zero human interaction. SABnzbd offers an easy setup wizard and has self-analysis tools to verify your setup.
  developer: Sabnzbd Team
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Sabnzbd/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Sabnzbd/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Sabnzbd/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Sabnzbd/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Sabnzbd/thumbnail.jpg
  tagline:
    en_us: Free and easy binary newsreader
  tips: {}
  title:
    en_us: Sabnzbd
  port_map: "8282"
