name: readarr
services:
  readarr:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/readarr:1.0.1126
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8787
        published: "8787"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/readarr/config
        target: /config
      - type: bind
        source: /path/to/books
        target: /books
      - type: bind
        source: /DATA/Downloads
        target: /downloads
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
      ports:
        - container: "8787"
          description:
            en_us: ""
      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /books
          description:
            en_us: ""
        - container: /downloads
          description:
            en_us: ""
    container_name: readarr
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: readarr
  author: Mypancho.com
  category: Media
  description:
    en_us: Readarr is a ebook collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new books from your favorite authors and will interface with clients and indexers to grab, sort, and rename them.
  developer: Readarr Team
    icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Readarr/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Readarr/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Readarr/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Readarr/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Readarr/thumbnail.png
  tagline:
    en_us: Ebook and audiobook collection manager for Usenet and BitTorrent users.
  tips: {}
  title:
    en_us: Readarr
  port_map: "8787"