name: diskover
services:
  app:
    image: linuxserver/diskover:2.1.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ES_HOST: ''
      ES_PORT: ''
      ES_USER: ''
      ES_PASS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: ES_HOST
          description:
            en_us: ElasticSearch host (optional)
        - container: ES_PORT
          description:
            en_us: ElasticSearch port (optional)
        - container: ES_USER
          description:
            en_us: ElasticSearch username (optional)
        - container: ES_PASS
          description:
            en_us: ElasticSearch password (optional)
      volumes:
        - container: /config
          description:
            en_us: Specify the exact disk.  DO NOT USE /mnt/user/appdata either use /mnt/cache/appdata/ or /mnt/disk$/appdata/
        - container: /data
          description:
            en_us: 'Container Path: /data'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/diskover/config
        target: /config
      - type: bind
        source: /DATA/AppData/diskover/data
        target: /data
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: An open source file system indexer that uses Elasticsearch to index and manage data across heterogeneous storage systems.
  tagline:
    en_us: Elasticsearch-based indexer for diverse storage system management.
  developer: diskoverteam
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/diskover/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/diskover/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/diskover/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/diskover/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/diskover/thumbnail.jpg
  title:
    en_us: Diskover
  category: Utility
  project_url: https://github.com/shirosaidev/diskover
  port_map: '80'
