name: uptimekuma
services:
  uptimekuma:
    image: louislam/uptime-kuma:1.23.2
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: bridge
    ports:
      - target: 3001
        published: "3001"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/app/data
        target: /app/data
    x-casaos:
      ports:
        - container: "3001"
          description:
            en_us: WebUI Port
      volumes:
        - container: /app/data
          description:
            en_us: Uptime Kuma data directory.
    container_name: uptimekuma
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: uptimekuma
  author: Mypancho.com
  category: Network
  description:
    en_us: It is a self-hosted monitoring tool like "Uptime Robot".
  developer: Louis Lam
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/UptimeKuma/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/UptimeKuma/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/UptimeKuma/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/UptimeKuma/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/UptimeKuma/thumbnail.png
  tagline:
    en_us: UptimeKuma:A fancy monitoring tool
  tips: {}
  title:
    en_us: Uptime Kuma
  index: /
  port_map: "3001"
