name: privatebin
services:
  app:
    image: privatebin/nginx-fpm-alpine:1.6.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ''
        - container: PGID
          description:
            en_us: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /srv/data
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /srv/cfg
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: PrivateBin is a minimalist, open source online pastebin where the server has zero knowledge of pasted data!
  tagline:
    en_us: |
      PrivateBin: Open-source minimalist online pastebin with data privacy.
  developer: Privatebin team
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/privatebin/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/privatebin/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/privatebin/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/privatebin/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/privatebin/thumbnail.png
  title:
    en_us: Privatebin
  category: Utility
  port_map: '8080'
