name: transmission
services:
  transmission:
    environment:
      PASS: casaos
      PEERPORT: "51413"
      PGID: "1000"
      PUID: "1000"
      TRANSMISSION_WEB_HOME: /transmission-web-control/
      TZ: Europe/London
      USER: casaos
    image: lscr.io/linuxserver/transmission:version-3.00-r5
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 9091
        published: "9091"
        protocol: tcp
      - target: 51413
        published: "51413"
        protocol: tcp
      - target: 51413
        published: "51413"
        protocol: UDP
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /DATA/Downloads/watch
        target: /watch
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
        - container: TRANSMISSION_WEB_HOME
          description:
            en_us: ""
        - container: USER
          description:
            en_us: ""
        - container: PASS
          description:
            en_us: ""
        - container: PEERPORT
          description:
            en_us: ""
      ports:
        - container: "9091"
          description:
            en_us: ""
        - container: "51413"
          description:
            en_us: ""
        - container: "51413"
          description:
            en_us: ""
          protocol: udp
      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /downloads
          description:
            en_us: ""
        - container: /watch
          description:
            en_us: ""
    container_name: transmission
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: transmission
  author: Mypancho.com
  category: Downloader
  description:
    en_us: |
      Transmission is an open source, volunteer-based project. Unlike some BitTorrent clients, Transmission doesn''t play games with its users to make money:  Transmission doesn''t bundle toolbars, pop-up ads, flash ads, twitter tools, or anything else. It doesn''t hold some features back for a payware version. Its source code is available for anyone to review. We don''t track our users, and our website and forums have no third-party ads or analytics.
  developer: Transmission
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Transmission/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Transmission/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Transmission/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Transmission/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Transmission/thumbnail.png
  tagline:
    en_us: Transmission is a cross-platform BitTorrent client
  tips:
    before_install:
      en_us: |
        | username | password |
        | -------- | -------- |
        | `casaos` | `casaos` |
  title:
    en_us: Transmission
  index: /
  port_map: "9091"
