name: wikijs
services:
  app:
    image: linuxserver/wikijs:2.5.300
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DB_TYPE: ''
      DB_HOST: ''
      DB_PORT: ''
      DB_NAME: ''
      DB_USER: ''
      DB_PASS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: DB_TYPE
          description:
            en_us: Set to sqlite (default) or postgres depending on the database engine you wish to use
        - container: DB_HOST
          description:
            en_us: DB hostname (postgres only)
        - container: DB_PORT
          description:
            en_us: DB port (postgres only)
        - container: DB_NAME
          description:
            en_us: DB name (postgres only)
        - container: DB_USER
          description:
            en_us: DB username (postgres only)
        - container: DB_PASS
          description:
            en_us: DB password (postgres only)
      volumes:
        - container: /config
          description:
            en_us: appdata
        - container: /data
          description:
            en_us: Where to store wiki data sqlite database
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/wikijs/config
        target: /config
      - type: bind
        source: /DATA/AppData/wikijs/data
        target: /data
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: A modern, lightweight and powerful wiki app built on NodeJS.
  tagline:
    en_us: Lightweight, powerful NodeJS wiki application with modern features.
  developer: Wikijs team
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/wikijs/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/wikijs/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/wikijs/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/wikijs/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/wikijs/thumbnail.jpg
  title:
    en_us: Wikijs
  category: Network
  project_url: https://wiki.js.org/
  port_map: '3000'
