name: synclounge
services:
  app:
    image: linuxserver/synclounge:5.2.5
    restart: unless-stopped
    environment:
      AUTH_LIST: ''
      AUTOJOIN_ENABLED: ''
      AUTOJOIN_ROOM: ''
    x-casaos:
      envs:
        - container: AUTH_LIST
          description:
            en_us: If set, only the users defined here and the users of the plex servers defined here will be able to access the server. Use e-mails, plex usernames and/or plex server machine ids, comma separated, no spaces.
        - container: AUTOJOIN_ENABLED
          description:
            en_us: DEPRECATED - (Still works but will be removed in the future in favor of the built-in var autojoin__room) - Set to true to let users autojoin the server and a room (specified by the AUTOJOIN_ROOM var).
        - container: AUTOJOIN_ROOM
          description:
            en_us: DEPRECATED - (Still works but will be removed in the future in favor of the built-in var autojoin__room) - Set the room name for auto joining (requires AUTOJOIN_ENABLED set to true).
      ports:
        - container: '8088'
          description:
            en_us: 'Container Port: 8088'
    ports:
      - target: 8088
        published: 8088
        protocol: tcp
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: A third party tool that allows you to watch Plex in sync with your friends/family, wherever you are.
  tagline:
    en_us: Third-party tool for synchronized Plex viewing with friends/family.
  developer: Samcm 
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/synclounge/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/synclounge/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/synclounge/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/synclounge/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/synclounge/thumbnail.jpg
  title:
    en_us: Synclounge
  category: Media
  project_url: https://github.com/samcm/synclounge
  port_map: '8088'
