name: crafty
version: "3"
services:
  crafty:
    container_name: crafty-container
    image: registry.gitlab.com/crafty-controller/crafty-4:4.1.3
    restart: always
    environment:
      - TZ=Etc/UTC
    ports:
      - "8110:8000"
      - "8111:8443"
      - "8112:8123"
      - 19132:19132/udp
      - 25500-25600:25500-25600
    volumes:
      - /DATA/AppData/Panchocloud/crafty/backups:/crafty/backups
      - /DATA/AppData/Panchocloud/crafty/logs:/crafty/logs
      - /DATA/AppData/Panchocloud/crafty/servers:/crafty/servers
      - /DATA/AppData/Panchocloud/crafty/config:/crafty/app/config
      - /DATA/AppData/Panchocloud/crafty/import:/crafty/import
    x-casaos:
      ports:
        - container: "8000"
          description:
            en_us: WebUI HTTP Port
          protocol: tcp
        - container: "19132"
          description:
            en_us: Minecraft Bedrock listening Port (UDP)
          protocol: udp
        - container: "25565"
          description:
            en_us: Minecraft listening Port (TCP)
          protocol: tcp
        - container: "25566"
          description:
            en_us: Minecraft listening Port (TCP)
          protocol: tcp
        - container: "25567"
          description:
            en_us: Minecraft listening Port (TCP)
          protocol: tcp
        - container: "25568"
          description:
            en_us: Minecraft listening Port (TCP)
          protocol: tcp
        - container: "25569"
          description:
            en_us: Minecraft listening Port (TCP)
          protocol: tcp
        - container: "25570"
          description:
            en_us: Minecraft listening Port (TCP)
          protocol: tcp
        - container: "25565"
          description:
            en_us: Minecraft listening Port (UDP)
          protocol: udp
        - container: "25566"
          description:
            en_us: Minecraft listening Port (UDP)
          protocol: udp
        - container: "25567"
          description:
            en_us: Minecraft listening Port (UDP)
          protocol: udp
        - container: "25568"
          description:
            en_us: Minecraft listening Port (UDP)
          protocol: udp
        - container: "25569"
          description:
            en_us: Minecraft listening Port (UDP)
          protocol: udp
        - container: "25570"
          description:
            en_us: Minecraft listening Port (UDP)
          protocol: udp
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: crafty
  author: Mypancho.com
  category: Games
  description:
    en_us: Crafty is an open source Minecraft control panel built using Tornado and AdminLTE, featuring server scheduling, a interactive console and the ability to run almost any type of Minecraft server
  developer: Crafty Team
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Crafty/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Crafty/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Crafty/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Crafty/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Crafty/thumbnail.png
  tagline:
    en_us: Take control of your Minecraft servers.
  tips:
    before_install:
      en_us: |
        Default Account
        | Username | Password |
        |----------|----------|
        | `admin`  | `crafty` |
  title:
    en_us: Crafty
  index: /panel
  scheme: https
  port_map: "8111"