name: LinuxServer-Grav
services:
  app:
    image: linuxserver/grav:1.7.42
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Contains all relevant configuration files.
      ports:
        - container: '80'
          description:
            en_us: Port for web frontend
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/grav/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://github.com/orgs/linuxserver/packages/container/package/grav'
  tagline:
    en_us: A Fast, Simple, and Flexible, file-based Web-platform.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/grav-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/grav-logo.png
  title:
    en_us: Grav
  category: LinuxServer.io
  project_url: https://github.com/getgrav/grav/
  port_map: '80'
