name: steamos
services:
  app:
    image: linuxserver/steamos:version-2023-09-15
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DRINODE: ''
      HOST_IP: ''
      STARTUP: ''
      RESOLUTION: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: DRINODE
          description:
            en_us: Specify the render device (GPU) for the contianer to use.
        - container: HOST_IP
          description:
            en_us: Specify the IP of the host, needed for LAN Remote Play.
        - container: STARTUP
          description:
            en_us: KDE to boot into desktop mode, BIGPICTURE to boot into gamescope.
        - container: RESOLUTION
          description:
            en_us: When booting into BIGPICTURE mode the screen resolution will be bound to this value.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/steamos/config
        target: /config
      - type: bind
        source: /dev/input
        target: /dev/input
      - type: bind
        source: /run/udev/data
        target: /run/udev/data
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: SteamOS is an Arch based Linux distribution made by Valve Software. This container is a vanilla Arch install with Steam repositories added for software support. This container will only work with modern AMD/Intel GPUs on a real Linux Host
  tagline:
    en_us: Valve's Arch-based Linux distro with enhanced software support.
  developer: Steamos team
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/SteamOS/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/SteamOS/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/SteamOS/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/SteamOS/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/SteamOS/thumbnail.png
  title:
    en_us: Steamos
  category: Utility