name: davos
services:
  app:
    image: linuxserver/davos:2.2.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /download
          description:
            en_us: 'Container Path: /download'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/davos/config
        target: /config
      - type: bind
        source: /DATA/AppData/davos/download
        target: /download
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: An FTP automation tool that periodically scans given host locations for new files. It can be configured for various purposes, including listening for specific files to appear in the host location, ready for it to download and then move, if required. It also supports completion notifications as well as downstream API calls, to further the workflow.
  tagline:
    en_us: FTP automation tool for scheduled host file monitoring and handling.
  developer: Davosteam
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/davos/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/davos/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/davos/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/davos/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/davos/thumbnail.png

  title:
    en_us: Davos
  category: Automation
  project_url: https://github.com/linuxserver/davos
  port_map: '8080'
