name: bazarr
services:
  bazarr:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/bazarr:1.3.0
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 6767
        published: "6767"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Media/Movies
        target: /movies
      - type: bind
        source: /DATA/Media/TV Shows
        target: /tv
      - type: bind
        source: /DATA/AppData/Panchocloud/bazarr/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
      ports:
        - container: "6767"
          description:
            en_us: ""
      volumes:
        - container: /movies
          description:
            en_us: ""
        - container: /tv
          description:
            en_us: ""
        - container: /config
          description:
            en_us: ""
    container_name: bazarr
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: bazarr
  author: Mypancho.com
  category: Media
  description:
    en_us: Bazarr is a companion application to Sonarr and Radarr. It can manage and download subtitles based on your requirements. You define your preferences by TV show or movie and Bazarr takes care of everything for you.
  developer: Sabnzbd Team
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Bazarr/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Bazarr/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Bazarr/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Bazarr/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Bazarr/thumbnail.jpg
  tagline:
    en_us: Letter generators for Sonarr and Radarr
  tips: {}
  title:
    en_us: Bazarr
  port_map: "6767"
