name: bazarr
services:
  bazarr:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: America/New_York
    image: linuxserver/bazarr:1.3.0
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 6767
        published: "6767"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Media/Movies
        target: /movies
      - type: bind
        source: /DATA/Media/TV Shows
        target: /tv
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
      ports:
        - container: "6767"
          description:
            en_us: ""
      volumes:
        - container: /movies
          description:
            en_us: ""
        - container: /tv
          description:
            en_us: ""
        - container: /config
          description:
            en_us: ""
    container_name: bazarr
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: bazarr
  author: Mypancho.com
  category: Media
  description:
    en_us: Elevate your Sonarr and Radarr experience with Bazarr, your perfect companion app! This powerhouse manages and fetches subtitles exactly as you want. Customize your preferences for TV shows and movies, and let Bazarr handle the rest. Say goodbye to the hassle – Bazarr ensures you always have the right subtitles at your fingertips. Enjoy your media without missing a beat, thanks to Bazarr's seamless integration. Simplify your entertainment experience today!
  developer: Sabnzbd Team
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Bazarr/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Bazarr/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Bazarr/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Bazarr/screenshot-3.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Bazarr/screenshot-4.png
  tagline:
    en_us: Effortless Letter Generation for Sonarr and Radarr Users.
    thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Bazarr/thumbnail.png
  tips: {}
  title:
    en_us: Bazarr
  port_map: "6767"
