name: duplicati
services:
  duplicati:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/duplicati:2.0.7
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8200
        published: "8200"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Duplicati/backups
        target: /backups
      - type: bind
        source: /DATA/Duplicati/source
        target: /source
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
      ports:
        - container: "8200"
          description:
            en_us: ""
      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /backups
          description:
            en_us: ""
        - container: /source
          description:
            en_us: ""
    container_name: duplicati
x-casaos:
  architectures:
    - amd64
    - arm64
  main: duplicati
  author: Mypancho.com
  category: Cloud
  description:
    en_us: Duplicati is a free, open source, backup client that securely stores encrypted, incremental, compressed backups on cloud storage services and remote file servers.
  developer: duplicati
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Duplicati/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Duplicati/screenshot-1.png
    - https    ://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Duplicati/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Duplicati/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Duplicati/thumbnail.png
  tagline:
    en_us: Store securely encrypted backups in the cloud!
  tips: {}
  title:
    en_us: Duplicati
  index: /
  port_map: "8200"
