name: qbittorrent
services:
  qbittorrent:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
      UMASK: "002"
    image: hotio/qbittorrent:release-4.5.2
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
      - target: 8080
        published: "8181"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/config
        target: /config
      - type: bind
        source: /DATA
        target: /DATA
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
        - container: PUID
          description:
            en_us: Run qBittorrent as specified uid.
        - container: PGID
          description:
            en_us: Run qBittorrent as specified gid.
        - container: UMASK
          description:
            en_us: Run qBittorrent as specified UMASK.
      ports:
        - container: "8080"
          description:
            en_us: WebUI HTTP Port
      volumes:
        - container: /config
          description:
            en_us: qBittorrent config directory.
        - container: /DATA
          description:
            en_us: qBittorrent Accessible directory.
    container_name: qbittorrent
x-casaos:
  architectures:
    - amd64
    - arm64
  main: qbittorrent
  author: CasaOS Team
  category: Downloader
  description:
    en_us: The qBittorrent project aims to provide an open-source software alternative to µTorrent.
  developer: qBittorrent
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/qBittorrent/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/qBittorrent/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/qBittorrent/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/qBittorrent/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/qBittorrent/thumbnail.png
  tagline:
    en_us: Free BitTorrent downloader
  tips:
    before_install:
      en_us: |
        Default Account

        | Username | Password |
        |----------|----------|
        | `admin`  | `adminadmin` |

        Default Accessible Path in qBittorrent

        | Name | Value |
        | ---- | ----- |
        | DATA Path | `/DATA` |
        | Downloads Path | `/DATA/Downloads` |
        | Media Path | `/DATA/Media` |

        The paths of other DATA subdirectories in CasaOS are also similar.
        Please make sure you use the correct path when using qBittorrent.
      zh_cn: |
        默认账号

        | 用户名 | 密码 |
        |----------|----------|
        | `admin`    | `adminadmin` |

        qBittorrent 默认可访问路径

        | 名称 | 值 |
        | ---- | ----- |
        | DATA 路径 | `/DATA` |
        | 下载路径 | `/DATA/Downloads` |
        | 媒体路径 | `/DATA/Media` |

        CasaOS 其他 DATA 子目录的路径也类似。
        请确保在使用 qBittorrent 时使用正确的路径。
  title:
    en_us: qBittorrent
  index: /
  port_map: "8181"
