name: sickchill
services:
  sickchill:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/sickchill:2023.6.27
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8081
        published: "8081"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/sickchill/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /DATA/Media/TV Shows
        target: /tv
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
      ports:
        - container: "8081"
          description:
            en_us: ""
      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /downloads
          description:
            en_us: ""
        - container: /tv
          description:
            en_us: ""
    container_name: sickchill
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: sickchill
  author: Mypancho.com
  category: Media
  description:
    en_us: |
      SickChill is an automatic Video Library Manager for TV Shows. It watches for new episodes of your favorite shows, and when they are posted it does its magic: automatic torrent/nzb searching, downloading, and processing at the qualities you want.
  developer: Sickchill Team
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Sickhill/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Sickhill/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Sickhill/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Sickhill/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/Sickhill/thumbnail.png
  tagline:
    en_us: Automatic video library manager for TV Shows
  tips: {}
  title:
    en_us: Sickchill
  port_map: "8081"