name: netbootxyz
services:
  app:
    image: linuxserver/netbootxyz:0.6.8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MENU_VERSION: ''
      PORT_RANGE: ''
      SUBFOLDER: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: MENU_VERSION
          description:
            en_us: Specify a specific version of boot files you want to use from NETBOOT.XYZ (unset pulls latest)
        - container: PORT_RANGE
          description:
            en_us: Specify the port range tftp will use for data transfers (see Wikipedia)
        - container: SUBFOLDER
          description:
            en_us: Specify a sobfolder if running this behind a reverse proxy (IE /proxy/)
      volumes:
        - container: /config
          description:
            en_us: appdata
        - container: /assets
          description:
            en_us: Path to mirrored assets (optional)
      ports:
        - container: '3000'
          description:
            en_us: Web Application (Default 3000)
        - container: '69'
          description:
            en_us: TFTP server
        - container: '8080'
          description:
            en_us: Webserver for local asset hosting (Default 8080)
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 69
        published: 69
        protocol: udp
      - target: 8080
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/netbootxyz/config
        target: /config
      - type: bind
        source: /DATA/AppData/netbootxyz/assets
        target: /assets
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: A way to PXE boot various operating system installers or utilities from one place within the BIOS without the need of having to go retrieve the media to run the tool. IPXE is used to provide a user friendly menu from within the BIOS that lets you easily choose the operating system you want along with any specific types of versions or bootable flags.
  tagline:
    en_us: PXE booting tool offering BIOS-based operating system selection.
  developer: Netbootxyzteam
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/netbootxyz/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/netbootxyz/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/netbootxyz/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/netbootxyz/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/netbootxyz/thumbnail.png
  title:
    en_us: Netbootxyz
  category: Utilities
  project_url: https://netboot.xyz/
  port_map: '3000'
