name: virtualmin
services:
  virtualmin:
    cpu_shares: 90
    command:
      - /bin/bash
      - -c
      - |
        service apache2 start && 
        service webmin start && 
        systemctl start fstrim.service && 
        systemctl start fail2ban && 
        systemctl start motd-news.timer && 
        systemctl start milter-greylist && 
        systemctl start usermin && 
        systemctl start mariadb && 
        service php8.1-fpm start && 
        systemctl start basic.target && 
        systemctl start sockets.target && 
        systemctl start slices.target && 
        systemctl start saslauthd && 
        systemctl start paths.target && 
        systemctl start motd-news.timer && 
        service bind9 start && 
        systemctl start postfix && 
        service dovecot start && 
        tail -f /dev/null
    container_name: virtualmin
    deploy:
      resources:
        limits:
          memory: 1915M
    image: mypancho/virtualmin:v2.3
    ports:
      - target: 80
        published: "8020"
        protocol: tcp
      - target: 443
        published: "8021"
        protocol: tcp
      - target: 10000
        published: "8022"
        protocol: tcp
      - target: 25
        published: "8025"
        protocol: tcp
      - target: 53
        published: "8024"
        protocol: tcp
      - target: 53
        published: "8025"
        protocol: udp
      - target: 20
        published: "8026"
        protocol: tcp
      - target: 110
        published: "8027"
        protocol: tcp
      - target: 111
        published: "8028"
        protocol: tcp
      - target: 143
        published: "8029"
        protocol: tcp
      - target: 21
        published: "8030"
        protocol: tcp
      - target: 587
        published: "8031"
        protocol: tcp
      - target: 993
        published: "8032"
        protocol: tcp
      - target: 995
        published: "8033"
        protocol: tcp
      - target: 3306
        published: "8034"
        protocol: tcp
      - target: 22
        published: "8035"
        protocol: tcp
      - target: 20000
        published: "8036"
        protocol: tcp
      - target: 38532
        published: "8037"
        protocol: tcp
      - target: 40259
        published: "8038"
        protocol: tcp
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    volumes: []
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
x-casaos:
  author: Mypancho.com
  category: Hosting
  hostname: "virtualmin"
  icon: ""
  index: /
  port_map: "8022"
  scheme: http
  store_app_id: virtualmin
  title:
    custom: Virtualmin
