name: pihole
services:
  pihole:
    environment:
      PROXY_LOCATION: pi.hole
      TZ: $TZ
      VIRTUAL_HOST: pi.hole
      WEBPASSWORD: casaos
    image: pihole/pihole:2023.05.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 80
        published: "8800"
        protocol: tcp
      - target: 53
        published: "53"
        protocol: tcp
      - target: 53
        published: "53"
        protocol: udp
      - target: 67
        published: "67"
        protocol: udp
      - target: 547
        published: "547"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/etc/pihole/
        target: /etc/pihole
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/etc/dnsmasq.d/
        target: /etc/dnsmasq.d
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
        - container: WEBPASSWORD
          description:
            en_us: Pi-hole admin password
        - container: VIRTUAL_HOST
          description:
            en_us: Pi-hole Custom Hostname
        - container: PROXY_LOCATION
          description:
            en_us: Pi-hole PROXY_LOCATION
      ports:
        - container: "80"
          description:
            en_us: WebUI HTTP Port
        - container: "53"
          description:
            en_us: Pihole DNS port
        - container: "53"
          description:
            en_us: Pihole DNS port
          protocol: udp
        - container: "67"
          description:
            en_us: Pihole DHCP IPv4 port
          protocol: udp
        - container: "547"
          description:
            en_us: Pihole DHCP IPv6 port
          protocol: udp
      volumes:
        - container: /etc/pihole
          description:
            en_us: Pi-hole /etc/pihole directory.
        - container: /etc/dnsmasq.d
          description:
            en_us: Pi-hole /etc/dnsmasq.d directory.
    container_name: pihole
x-casaos:
  architectures:
    - amd64
    - arm64
    - "386"
    - arm
  main: pihole
  author: Mypancho.com
  category: Network
  description:
    en_us: Open source home automation that puts local control and privacy first. Powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect to run on a Raspberry Pi or a local server.
  developer: Pi-hole
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Pihole/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Pihole/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Pihole/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Pihole/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Pihole/thumbnail.png
  tagline:
    en_us: Network-wide Ad Blocking
  tips:
    before_install:
      en_us: |
        Default password: `casaos`
  title:
    en_us: Pi-hole
  index: /admin
  port_map: "8800"
