name: couchpotato
services:
  couchpotato:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: $TZ
    image: linuxserver/couchpotato:version-7260c12f
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 5050
        published: "5050"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Media/Movies
        target: /movies
      - type: bind
        source: /DATA/Downloads
        target: /downloads
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
            zh_cn: 时区
        - container: PUID
          description:
            en_us: Run CouchPotato as specified uid.
        - container: PGID
          description:
            en_us: Run CouchPotato as specified gid.
      ports:
        - container: "5050"
          description:
            en_us: WebUI HTTP Port
      volumes:
        - container: /config
          description:
            en_us: CouchPotato config directory.
        - container: /movies
          description:
            en_us: CouchPotato movies directory.
        - container: /downloads
          description:
            en_us: CouchPotato downloads directory.
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: couchpotato
  author: Mypancho.com
  category: Media
  description:
    en_us: Awesome PVR for usenet and torrents. Just fill in what you want to see and CouchPotato will add it to your want to watch-list. Every day it will search through multiple sources, looking for the best possible match. If available, it will send it using your favorite download software.
  developer: CouchPotato
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Cloudflared/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/CouchPotato/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/CouchPotato/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/CouchPotato/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/CouchPotato/thumbnail.png
  tagline:
    en_us: Automatically find movies you want to watch
  tips: {}
  title:
    en_us: CouchPotato
  index: /
  port_map: "5050"
