name: chatbot-ui
services:
  chatbot-ui:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: ghcr.io/mckaywrigley/chatbot-ui@sha256:8c60abae8a34fd43f7015c124e0b972839e0efb35c06cd31cd1ec1ed9a57ceeb
    network_mode: bridge
    ports:
      - target: 3000
        published: "3080"
        protocol: tcp
    restart: unless-stopped
    x-casaos:
      ports:
        - container: "3000"
          description:
            en_us: WebUI HTTP Port
    container_name: chatbot-ui
x-casaos:
  architectures:
    - amd64
    - arm64
  main: chatbot-ui
  author: Mypancho.com
  category: Chat
  description:
    en_us: Chatbot UI is an open source chat UI for AI models.
  developer: Mckay Wrigley
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/ChatbotUI/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/ChatbotUI/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/ChatbotUI/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/ChatbotUI/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/ChatbotUI/thumbnail.png
  tagline:
    en_us: Open source chat UI for AI models
  title:
    en_us: Chatbot UI
  index: /
  port_map: "3080"
