name: homeassistant
services:
  homeassistant:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: linuxserver/homeassistant:2023.9.3
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
        - container: PUID
          description:
            en_us: Run HomeAssistant as specified uid.
        - container: PGID
          description:
            en_us: Run HomeAssistant as specified gid.
      volumes:
        - container: /config
          description:
            en_us: HomeAssistant config directory.
    container_name: homeassistant
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: homeassistant
  author: Mypancho.com
  category: Home Automation
  description:
    en_us: Open source home automation that puts local control and privacy first. Powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect to run on a Raspberry Pi or a local server.
  developer: Home Assistant
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/HomeAssistant/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/HomeAssistant/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/HomeAssistant/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/HomeAssistant/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/HomeAssistant/thumbnail.jpg
  tagline:
    en_us: Awaken your home
  tips: {}
  title:
    en_us: Home Assistant
  index: /
  port_map: "8123"
