name: netdata
services:
  app:
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    cpu_shares: 90
    container_name: netdata
    deploy:
      resources:
        limits:
          memory: 1794M
    image: netdata/netdata:stable
    labels:
      icon: https://icon.casaos.io/main/all/netdata.png
    pid: host
    ports:
      - target: 19999
        published: "19999"
        protocol: tcp
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/Netdata/config
        target: /etc/netdata
      - type: bind
        source: /DATA/AppData/Panchocloud/Netdata/lib
        target: /var/lib/netdata
      - type: bind
        source: /DATA/AppData/Panchocloud/Netdata/cache
        target: /var/cache/netdata
      - type: bind
        source: /etc/passwd
        target: /host/etc/passwd
      - type: bind
        source: /etc/group
        target: /host/etc/group
      - type: bind
        source: /proc
        target: /host/proc
      - type: bind
        source: /sys
        target: /host/sys
      - type: bind
        source: /etc/os-release
        target: /host/etc/os-release
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  author: Mypancho.com
  category: Utilities
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Netdata/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Netdata/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Netdata/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Netdata/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Netdata/thumbnail.png
  index: /
  port_map: "19999"
  scheme: http
  store_app_id: netdata
  title:
    custom: Netdata