name: red-discordbot
services:
  app:
    container_name: red-discordbot
    image: phasecorex/red-discordbot:full
    environment:
      - PREFIX=.
      - PUID=$PUID
      - PGID=$PGID
      - TOKEN=<your-discord-token>
      - TZ=$TZ
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/data
        target: /data
    restart: unless-stopped
    privileged: false

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: Mypancho.com
  category: Utility
  description:
    en_us: Red-DiscordBot is an open-source and customizable bot for the popular gaming communication platform, Discord. It offers a wide range of features including music streaming, moderation tools, utilities, role management, and much more. Users can easily install and configure the bot to suit their server's needs. With a dedicated and active community of developers, Red-DiscordBot continues to evolve and improve, ensuring a seamless and enjoyable experience for Discord users looking to enhance their server's capabilities.
  developer: red-discordbot
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/red-discordbot/icon.png
  index: /
  main: app
  port_map: ""
  scheme: http
  tagline:
    en_us: Red is a fully modular bot meaning all features and commands can be enabled/disabled to your liking, making it completely customizable.
  store_app_id: red-discordbot-Panchocloud
  title:
    en_us: Red Discord Bot
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/red-discordbot/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/red-discordbot/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/red-discordbot/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/red-discordbot/thumbnail.jpg