# Configuration for big-bear-baserow setup
name: baserow

# Service definitions for the big-bear-baserow application
services:
  # Service name: app
  app:
    # Set the name of the Docker container.
    container_name: baserow

    # Use the specified Docker image for Baserow and specify its version.
    image: baserow/baserow:1.20.0

    # Set environment variables for Baserow.
    environment:
      # Set the your CASA OS IP for Baserow to use.
      BASEROW_PUBLIC_URL: "http://[YOUR_CASAOS_IP]:7350"

    # Map ports from the host machine to the Baserow container.
    ports:
      - "7350:80" # Map port 7300 on the host to port 80 in the container.
      - "7351:443" # Map port 7301 on the host to port 443 in the container.

    # Define volumes to persist data between container restarts.
    volumes:
      - /DATA/AppData/$AppID/baserow/data:/baserow/data

# CasaOS specific configuration
x-casaos:
  architectures: # Supported CPU architectures
    - amd64
    - arm64
  main: app # Main service of the application
  description:
    en_us: Baserow is a user-friendly open-source no-code database solution that simplifies data management for businesses. With Baserow, creating customised database applications is a breeze, even for those without coding expertise. Additionally, it facilitates real-time collaboration with teams, allowing seamless teamwork. By automating workflows and streamlining data management, Baserow empowers businesses to make informed, data-driven decisions. # Description in English
  tagline:
    en_us: Open-source, no-code tool for easy data # Short description or tagline in English
  developer: "Baserow" # Developer's name or identifier
  author: Mypancho.com # Author of this configuration
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/baserow/icon.png # Icon for the application
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/baserow/screenshot-1.PNG
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/baserow/screenshot-2.PNG
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/baserow/screenshot-3.PNG
  thumbnail: "https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/baserow/thumbnail.PNG" # Thumbnail image
  title:
    en_us: Baserow # Title in English
  category: Management # Application category
  port_map: "7350" # Port mapping information
