name: nzbget
services:
  nzbget:
    environment:
      NZBGET_PASS: tegbzn6789
      NZBGET_USER: nzbget
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/nzbget:21.1.20230119
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 6789
        published: "6789"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/nzbget/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
        - container: NZBGET_USER
          description:
            en_us: ""
        - container: NZBGET_PASS
          description:
            en_us: ""
      ports:
        - container: "6789"
          description:
            en_us: ""
      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /downloads
          description:
            en_us: ""
    container_name: nzbget
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: nzbget
  author: Mypancho.com
  category: Downloader
  description:
    en_us: NZBGet can run on almost any device - classic PC, NAS, media player, SAT-receiver, WLAN-router, etc. The download area provides precompiled binaries for Windows, macOS, Linux (compatible with many CPUs and platform variants), FreeBSD and Android. For other platforms the program can be compiled from sources.
  developer: Nzbget Team
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Nzbget/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Nzbget/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Nzbget/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Nzbget/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Nzbget/thumbnail.png
  tagline:
    en_us: Efficient Usenet downloader
  tips:
    before_install:
      en_us: |
        Default Account

        | Username | Password |
        | -------- | -------- |
        | nzbget   | tegbzn6789 |
  title:
    en_us: Nzbget
  port_map: "6789"