name: syncthing
services:
  syncthing:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: linuxserver/syncthing:1.24.0
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
      - target: 8384
        published: "8384"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: udp
      - target: 21027
        published: "21027"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA
        target: /DATA
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
        - container: PUID
          description:
            en_us: Run Syncthing as specified uid.
        - container: PGID
          description:
            en_us: Run Syncthing as specified gid.
      ports:
        - container: "8384"
          description:
            en_us: WebUI HTTP Port
        - container: "22000"
          description:
            en_us: Syncthing listening Port (TCP)
        - container: "22000"
          description:
            en_us: Syncthing listening Port (UDP)
          protocol: udp
        - container: "21027"
          description:
            en_us: Syncthing protocol discovery Port (TCP)
          protocol: udp
      volumes:
        - container: /config
          description:
            en_us: Syncthing config directory.
        - container: /DATA
          description:
            en_us: Syncthing Accessible Directory
    container_name: syncthing
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: syncthing
  author: Mypancho.com
  category: Backup
  description:
    en_us: Syncthing is a continuous file synchronization program. It synchronizes files between two or more computers in real time, safely protected from prying eyes. Your data is your data alone and you deserve to choose where it is stored, whether it is shared with some third party, and how it's transmitted over the internet.
  developer: Syncthing
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Syncthing/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Syncthing/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Syncthing/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Syncthing/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Syncthing/thumbnail.png
  tagline:
    en_us: Free, secure, and distributed file synchronisation tool.  
  tips: {}
  title:
    en_us: Syncthing
  index: /
  port_map: "8384"
