name: excalidraw
services:
  excalidraw:
    environment:
      TZ: $TZ
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 80
        published: "5000"
        protocol: tcp
    restart: unless-stopped
x-casaos:
  architectures:
    - amd64
  main: excalidraw
  author: Mypancho.com
  category: Utilities
  description:
    en_us: Excalidraw is a virtual collaborative whiteboard tool that lets you easily sketch diagrams, illustrate ideas, and create beautiful illustrations remotely.
  developer: Excalidraw
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/excalidraw/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/excalidraw/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/excalidraw/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/excalidraw/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/excalidraw/thumbnail.png
  tagline:
    en_us: Collaborative whiteboard tool for remote diagram sketching.
  tips: {}
  title:
    en_us: Excalidraw
  index: /
  port_map: "5000"