name: media-fetch-pro
services:
  media-fetch-pro:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: correctroad/media-fetch-pro:0.3.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 7789
        published: "7789"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Media/MediaFetchPro
        target: /var/opt/video
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/config
        target: /var/opt/config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: timezone
      ports:
        - container: "7789"
          description:
            en_us: WebUI HTTP Port
      volumes:
        - container: /var/opt/video
          description:
            en_us: video download directory.
    container_name: mediafetchpro
x-casaos:
  architectures:
    - amd64
    - arm64
  main: media-fetch-pro
  author: Mypancho.com
  category: Media
  description:
    en_us: Media Fetch PRO is an application to download video of youtube, bilibili and more websites in future with metadata to jellyfin, emby, plex and more softwares in future. Project - https://github.com/Media-Fetch-Pro/Media-Fetch-Pro
  developer: CorrectRoadH
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/MediaFetchPro/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/MediaFetchPro/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/MediaFetchPro/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/MediaFetchPro/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/MediaFetchPro/thumbnail.png
  tagline:
    en_us: Media Fetch PRO is an application to download video of youtube, bilibili and more websites in future with metadata to jellyfin, emby, plex and more softwares in future.
  tips:
    before_install:
      en_us: Media Fetch PRO is in beta test yet. So you may lose your download history in the future and you may got some bugs.
  title:
    en_us: Media Fetch Pro
  port_map: "7789"