name: redis
services:
  app:
    image: redis:6.2.13
    restart: unless-stopped
    ports:
      - target: 6379
        published: '6379'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/redis/data
        target: /data
      - type: bind
        source: /DATA/AppData/redis/config
        target: /usr/local/etc/redis
x-casaos:
  architectures:
    - amd64
    - arm64
    - armhf
    - arm
    - '386'
  main: app
  description:
    en_us: Redis is an open source (BSD licensed), in-memory data structure store used as a database, cache, message broker, and streaming engine. Redis provides data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs, geospatial indexes, and streams. Redis has built-in replication, Lua scripting, LRU eviction, transactions, and different levels of on-disk persistence, and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster.
  tagline:
    en_us: BSD-licensed in-memory data store for caching and more.
  developer: Redis
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/redis/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/redis/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/redis/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/redis/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/redis/thumbnail.jpg
  category: Utility
  title:
    en_us: Redis
