name: emulatorjs
services:
  emulatorjs:
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - SUBFOLDER=/
      - TZ=$TZ
    image: lscr.io/linuxserver/emulatorjs:1.7.2
    network_mode: bridge
    ports:
      - target: 3000
        published: "3001"
        protocol: tcp
      - target: 4001
        published: "4001"
        protocol: tcp
      - target: 80
        published: "88"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/data
        target: /data
      - type: bind
        source: /ROMS/nes
        target: /data/nes/roms
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: Play Game
            zh_cn: 玩游戏
        - container: "3000"
          description:
            en_us: Manage ROMS
            zh_cn: ROM 管理
    container_name: emulatorjs
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  description:
    en_us: EmulatorJS is a Docker-based emulator application that can simulate various operating systems and device environments within containers for development, testing, and learning purposes.
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/EmulatorJS/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/EmulatorJS/screenshot-1.png
    - https    ://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/EmulatorJS/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/EmulatorJS/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/EmulatorJS/thumbnail.png
  tagline:
  en_us: Unlock the power of emulation with EmulatorJS – Explore, experiment, and innovate across diverse operating systems and device environments.
  author: Mypancho.com
  category: Utilities
  hostname: ""
  index: /
  port_map: "88"
  scheme: http
  store_app_id: emulatorjs
  title:
    en_us: emulatorjs
