name: tandoor
services:
  app:
    image: vabene1111/recipes:1
    restart: unless-stopped
    environment:
      SECRET_KEY: ''
      DB_ENGINE: django.db.backends.postgresql
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: casaos
      POSTGRES_PASSWORD: casaos
      POSTGRES_DB: casaos
    depends_on:
      - db
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/staticfiles
        target: /opt/recipes/staticfiles
      - type: bind
        source: /DATA/AppData/$AppID/mediafiles
        target: /opt/recipes/mediafiles
  db:
    image: postgres:16.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      POSTGRES_USER: casaos
      POSTGRES_PASSWORD: casaos
      POSTGRES_DB: casaos
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: POSTGRES_DB
          description:
            en_us: Specify the name of a database to be created on image startup.
        - container: POSTGRES_USER
          description:
            en_us: Postgres server username
        - container: POSTGRES_PASSWORD
          description:
            en_us: Postgres server password
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: Directory where Postgres database data is stored
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/postgres/data
        target: /var/lib/postgresql/data
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: The recipe manager that allows you to manage your ever growing collection of digital recipes.
  tagline:
    en_us: Recipe manager for organizing your digital recipe collection efficiently.
  developer: vabene1111
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/tandoor/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/tandoor/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/tandoor/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/tandoor/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/tandoor/thumbnail.png
  title:
    en_us: Tandoor
  category: Utility
  port_map: '8080'
