name: dillinger
services:
  app:
    image: linuxserver/dillinger:3.39.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: '8080'
          description:
            en_us: Webui - Default port 8080
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dillinger/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Dillinger, an online Markdown editor, functions directly in your web browser, eliminating the necessity of downloading software. Its dual-pane interface comprises an editor on the left and a live preview on the right, similar to StackEdit.
  tagline:
    en_us: A cloud-enabled, mobile-ready, offline-storage, AngularJS powered HTML5 Markdown editor.
  developer: dillingerteam
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/dillinger/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/dillinger/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/dillinger/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/dillinger/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/dillinger/thumbnail.jpg
  title:
    en_us: Dillinger
  category: Utility
  project_url: https://dillinger.io/
  port_map: '8080'
