name: paperless-ngx
services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:1.17.4
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - '8005:8000'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:8000
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /DATA/AppData/paperless/data:/usr/src/paperless/data
      - /DATA/AppData/paperless/media:/usr/src/paperless/media
      - /DATA/AppData/paperless/export:/usr/src/paperless/export
      - /DATA/AppData/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_DBPORT: 3306
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: admin
  broker:
    image: redis:7
    restart: unless-stopped
    volumes:
      - /DATA/AppData/paperless/redis/data:/data
  db:
    image: mariadb:11.1.2
    restart: unless-stopped
    volumes:
      - /DATA/AppData/paperless/mysql:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: paperless
  description:
    en_us: Paperless-ngx forked from paperless-ng to continue the great work and distribute responsibility of supporting and advancing the project among a team of people.
  tagline:
    en_us: Paperless-ngx: Document management system converting physical documents into digital archives.
  developer: paperless-ngx
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/paperless-ngx/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/paperless-ngx/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/paperless-ngx/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/paperless-ngx/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/paperless-ngx/thumbnail.png
  title:
    en_us: Paperless-ngx
  tips:
    before_install:
      en_us: |
        ## Credentials:

        username: `admin`

        password: `admin`
  category: Utility
  port_map: '8005'
