name: ldap-auth
services:
  app:
    image: linuxserver/ldap-auth:3.4.3
    restart: unless-stopped
    environment:
      FERNETKEY: ''
      CERTFILE: ''
      KEYFILE: ''
    x-casaos:
      envs:
        - container: FERNETKEY
          description:
            en_us: Optionally define a custom valid fernet key (only needed if container is frequently recreated, or if using multi-node setups, invalidating previous authentications)
        - container: CERTFILE
          description:
            en_us: Optionally point this to a certificate file to enable HTTP over SSL (HTTPS) for the ldap auth daemon
        - container: KEYFILE
          description:
            en_us: Optionally point this to the private key file, matching the certificate file referred to in CERTFILE
      ports:
        - container: '8888'
          description:
            en_us: LDAP auth daemon port
        - container: '9000'
          description:
            en_us: LDAP login page port
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 9000
        published: 9000
        protocol: tcp
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Software is for authenticating users who request protected resources from servers proxied by nginx. It includes a daemon (ldap-auth) that communicates with an authentication server, and a webserver daemon that generates an authentication cookie based on the user’s credentials. The daemons are written in Python for use with a Lightweight Directory Access Protocol (LDAP) authentication server (OpenLDAP or Microsoft Windows Active Directory 2003 and 2012).
  tagline:
    en_us: Authentication software for nginx-proxied servers, integrating LDAP functionality.
  developer: ldapteam
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/ldap-auth/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/ldap-auth/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/ldap-auth/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/ldap-auth/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/ldap-auth/thumbnail.png
  title:
    en_us: Ldap auth
  category: Utility
  project_url: https://github.com/nginxinc/nginx-ldap-auth
