name: lazylibrarian
services:
  lazylibrarian:
    environment:
      DOCKER_MODS: linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/lazylibrarian:version-a7d5948a
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 5299
        published: "5299"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /path/to/data
        target: /books
      - type: bind
        source: /DATA/AppData/Panchocloud/lazylibrarian/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
        - container: DOCKER_MODS
          description:
            en_us: ""
      ports:
        - container: "5299"
          description:
            en_us: ""
      volumes:
        - container: /downloads
          description:
            en_us: ""
        - container: /books
          description:
            en_us: ""
        - container: /config
          description:
            en_us: ""
    container_name: lazylibrarian
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: lazylibrarian
  author: Mypancho.com
  category: Downloader
  description:
    en_us: Lazylibrarian is a program to follow authors and grab metadata for all your digital reading needs. It uses a combination of Goodreads Librarything and optionally GoogleBooks as sources for author info and book info. This container is based on the DobyTang fork.
  developer: Lazylibrarian Team
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Lazylibrarian/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Lazylibrarian/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Lazylibrarian/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Lazylibrarian/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Lazylibrarian/thumbnail.png
  tagline:
    en_us: eBook Auto Downloader
  tips: {}
  title:
    en_us: Lazylibrarian
  port_map: "5299"
