name: gitea
services:
  gitea:
    environment:
      USER_GID: "1000"
      USER_UID: "1000"
    image: gitea/gitea:1.21.0-rc0-rootless
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
      - target: 3000
        published: "3002"
        protocol: tcp
      - target: 22
        published: "222"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Panchocloud/$AppID/data
        target: /data
    x-casaos:
      envs:
        - container: USER_UID
          description:
            en_us: The UID (Unix user ID) of the user that runs Gitea
        - container: USER_GID
          description:
            en_us: The GID (Unix group ID) of the user that runs Gitea
      ports:
        - container: "3000"
          description:
            en_us: WebUI Port
        - container: "22"
          description:
            en_us: SSH Port
      volumes:
        - container: /data
          description:
            en_us: Gitea data directory.
    container_name: gitea
x-casaos:
  architectures:
    - amd64
    - arm64
  main: gitea
  author: Mypancho.com
  category: Developer
  description:
    en_us: Gitea is a community managed lightweight code hosting solution written in Go.
  developer: Gitea
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Gitea/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Gitea/screenshot-1.png
    - https    ://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Gitea/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Gitea/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/Gitea/thumbnail.png
  tagline:
    en_us: Git with a cup of tea
  tips:
    before_install:
      en_us: |
        When the App is installed, the first account registered will become the administrator account.
  title:
    en_us: Gitea
  index: /
  port_map: "3002"
